version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php artisan octane:frankenphp --max-requests=1
    ports:
      - "8011:8000"
    volumes:
      - .:/app
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - "${DB_PORT}:5432"
#    environment:
#      POSTGRES_PASSWORD: "${DB_PASSWORD}"
#      POSTGRES_DB: "${DB_DATABASE}"
#  redis:
#    image: redis
#    restart: always
#    ports:
#      - "${REDIS_PORT}:6379"
