export const states = {
    "hong_kong": [
        "Central and Western",
        "Eastern",
        "Southern",
        "Wan Chai",
        "Sham Shui Po",
        "Kowloon City",
        "Kwun Tong",
        "Wong Tai Sin",
        "Yau Tsim Mong",
        "Islands",
        "Kwai Tsing",
        "North",
        "Sai Kung",
        "Sha Tin",
        "Tai Po",
        "Tsuen Wan",
        "Tuen Mun",
        "Yuen Long"
    ],
    "indonesia": [
        "Aceh",
        "Bali",
        "Bangka Belitung Islands",
        "Banten",
        "Bengkulu",
        "Central Java",
        "Central Kalimantan",
        "Central Sulawesi",
        "East Java",
        "East Kalimantan",
        "East Nusa Tenggara",
        "Gorontalo",
        "Special Capital Region of Jakarta",
        "Jambi",
        "Lampung",
        "Maluku",
        "North Kalimantan",
        "North Maluku",
        "North Sulawesi",
        "North Sumatra",
        "Papua",
        "Riau",
        "Riau Islands",
        "Southeast Sulawesi",
        "South Kalimantan",
        "South Sulawesi",
        "South Sumatra",
        "West Java",
        "West Kalimantan",
        "West Nusa Tenggara",
        "West Papua",
        "West Sulawesi",
        "West Sumatra",
        "Special Region of Yogyakarta"
    ]
}
